' DATA FOR MOUSE MOVEMENT X AND Y POSITIONS IN LESSON 5 SHOW ME STEPS :

xy = Array(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)

' Step 3: MOUSE MOVES TO ONLINE SERVICES ICON
xy(0) = 220
xy(1) = 115
xy(2) = 115
xy(3) = 23


' Step 5: MOUSE MOVES TO CLOSE ONLINE SERVICES
xy(4) = 384
xy(5) = 22


' Step 6: MOUSE MOVES TO 'THE INTERNET'
xy(6) = 39
xy(7) = 164


' Step 7: MOUSE MOVES TO ADDRESS BOX
xy(8) = 175
xy(9) = 121


' Step 8: MOUSE MOVES TO 'TODAY'S LINKS'
xy(10) = 200
xy(11) = 145


' Step 9: MOUSE MOVES TO 'PRODUCT NEWS'
xy(12) = 315
xy(13) = 115


' Step 10: MOUSE MOVES TO BACK BUTTON
xy(14) = 58
xy(15) = 82

' Step 10: MOUSE MOVES TO FORWARD BUTTON
xy(16) = 140
xy(17) = 82


' Step 11: MOUSE MOVES TO 'BEST OF THE WEB' BUTTON
xy(18) = 340
xy(19) = 150


' Step 12: MOUSE MOVES TO SCROLLBAR
xy(20) = 461
xy(21) = 217

' Step 12: MOUSE MOVES TO LINK1
xy(22) = 401
xy(23) = 213

' Step 12: MOUSE MOVES TO LINK2
xy(24) = 323
xy(25) = 232

' Step 12: MOUSE MOVES TO LINK3
xy(26) = 242
xy(27) = 259

' Step 12: MOUSE MOVES TO LINK4
xy(28) = 94
xy(29) = 260

' Step 12: MOUSE MOVES TO LINK5
xy(30) = 95
xy(31) = 234

' Step 12: MOUSE MOVES TO LINK6
xy(32) = 101
xy(33) = 215

' Step 12: MOUSE MOVES TO LINK7
xy(34) = 71
xy(35) = 196


' Step 13: MOUSE MOVES TO HOME BUTTON
xy(36) = 307
xy(37) = 86


' Step 14: MOUSE MOVES TO IE CLOSE BUTTON
xy(38) = 461
xy(39) = 32

